-- ============================================================
-- Security fix (Sep 2026): private document buckets
--
-- Run ONCE in the Supabase SQL editor AFTER deploying the matching app
-- changes (branch fix/auth-holes-2). From that deploy on:
--   * lease documents and energy-bill PDFs are served through short-lived
--     signed URLs generated by authenticated API routes
--   * nothing reads these two buckets with the anon/authenticated role
--
-- Idempotent: safe to re-run.
-- ============================================================

-- 1. Make the fully server-mediated buckets private.
UPDATE storage.buckets
SET public = false
WHERE id IN ('lease-documents', 'energy-bills');

-- 2. Drop the role-wide policies on lease-documents: they let ANY signed-in
--    user read/insert/delete ANY object in the bucket. All access now goes
--    through the service role in /api/leases/[id]/documents.
DROP POLICY IF EXISTS "Authenticated users can upload lease documents" ON storage.objects;
DROP POLICY IF EXISTS "Authenticated users can view lease documents"   ON storage.objects;
DROP POLICY IF EXISTS "Authenticated users can delete lease documents" ON storage.objects;

-- 3. NOT changed here (follow-up): the 'documents' bucket.
--    It mixes sensitive files (matrículas, IPTU, identity docs, agency
--    agreements under agencies/<id>/agreements/) with property photos and
--    videos that the UI renders from public URLs (photos/<profileId>/…,
--    videos/<profileId>/…). Flipping it private would break every gallery.
--    Plan: move photos/videos to a public 'property-media' bucket, rewrite
--    the stored URLs, then run:
--      UPDATE storage.buckets SET public = false WHERE id = 'documents';
--    and scope its policies by owner prefix instead of auth.role().

-- 4. Verify
SELECT id, public FROM storage.buckets ORDER BY id;

SELECT policyname, cmd, roles, qual, with_check
FROM pg_policies
WHERE schemaname = 'storage' AND tablename = 'objects'
ORDER BY policyname;
